version: '3.8'

services:
  # Service de la base de donn√©es
  db:
    image: mysql:8.0
    container_name: securesup-db
    restart: always
    environment:
      MYSQL_DATABASE: securesup_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Service du Backend
  backend:
    build: ./backend
    container_name: securesup-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root_password
      - DB_NAME=securesup_db
    depends_on:
      db:
        condition: service_healthy
  # Service du Frontend
  frontend:
    build: ./frontend
    container_name: securesup-frontend
    ports:
      - "80:3000" 
    stdin_open: true 
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - backend